"""Начальная схема: белый список, журнал модерации, размеченная выборка.

Revision ID: 0001
Revises: —
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_samples',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label', 'text_hash', name='uq_sample_text')
    )
    with op.batch_alter_table('message_samples', schema=None) as batch_op:
        batch_op.create_index('ix_samples_label', ['label'], unique=False)

    op.create_table('moderation_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('categories', sa.String(length=255), nullable=False),
    sa.Column('signals', sa.String(length=512), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('false_positive', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_chat_created', ['chat_id', 'created_at'], unique=False)

    op.create_table('whitelist_entries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', 'username', name='uq_whitelist_target')
    )
    with op.batch_alter_table('whitelist_entries', schema=None) as batch_op:
        batch_op.create_index('ix_whitelist_lookup', ['chat_id', 'user_id'], unique=False)
        batch_op.create_index('ix_whitelist_username', ['chat_id', 'username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_whitelist_username')
        batch_op.drop_index('ix_whitelist_lookup')

    op.drop_table('whitelist_entries')
    with op.batch_alter_table('moderation_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_chat_created')

    op.drop_table('moderation_events')
    with op.batch_alter_table('message_samples', schema=None) as batch_op:
        batch_op.drop_index('ix_samples_label')

    op.drop_table('message_samples')
    # ### end Alembic commands ###
